version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Bump"
    groups:
      junit:
        patterns:
          - "org.junit*"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.jacoco:*"
          - "com.qulice:*"
          - "org.sonatype.central:*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Bump"
    groups:
      actions:
        patterns:
          - "*"
